name: Build and Deploy Hugo to gh-pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.151.2'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # Hugo in this repo writes output to `docs/` (publishDir in hugo.toml).
          # Deploy that folder to the gh-pages branch so Pages serves the correct site.
          publish_dir: ./docs
          publish_branch: gh-pages
          allow_empty_commit: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
